FROM docker.io/debian:bookworm-slim as buildbox
RUN \
    apt-get update && \
    apt-get install -y make python3.11 binutils curl ca-certificates && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 311 && \
    mkdir -p /usr/src/klipper && \
    apt-get clean
