ARG BASE_IMAGE=kfa_buildbase:latest

from bitnami/minideb:latest as pruchain_downloader
  run install_packages git ca-certificates wget lbzip2 xz-utils
  run git clone https://github.com/dinuxbg/gnupru -b 2024.05 --depth 1 /usr/src/gnupru
  workdir /usr/src/gnupru
  env PREFIX=/opt/gnupru
  run ./download-and-prepare.sh

from bitnami/minideb:latest as pruchain_builder
  run install_packages git pv ca-certificates wget lbzip2 xz-utils gcc build-essential file texinfo libgmp-dev libmpfr-dev libmpc-dev
  copy --from=pruchain_downloader /usr/src/gnupru /usr/src/gnupru/
  workdir /usr/src/gnupru
  env PREFIX=/opt/gnupru
  run ./build.sh

from ${BASE_IMAGE}
  run install_packages libmpc3 libgmp10 libmpfr6
  copy --from=pruchain_builder /opt/gnupru /opt/gnupru/
  env PATH=${PATH}:/opt/gnupru/bin
