ARG BASE_IMAGE=kfa_buildbase:latest

FROM bitnami/minideb:latest as pruchain_downloader
RUN \
  apt-get update && \
  apt-get install -y git ca-certificates wget lbzip2 xz-utils && \
  apt-get clean
RUN git clone https://github.com/dinuxbg/gnupru -b 2024.05 --depth 1 /usr/src/gnupru
WORKDIR /usr/src/gnupru
ENV PREFIX=/opt/gnupru
RUN ./download-and-prepare.sh

from bitnami/minideb:latest as pruchain_builder
RUN \
  apt-get update && \
  apt-get install -y git pv ca-certificates wget lbzip2 xz-utils gcc build-essential file texinfo libgmp-dev libmpfr-dev libmpc-dev && \
  apt-get clean
COPY --from=pruchain_downloader /usr/src/gnupru /usr/src/gnupru/
WORKDIR /usr/src/gnupru
ENV PREFIX=/opt/gnupru
RUN ./build.sh

FROM ${BASE_IMAGE}
RUN \
  apt-get update && \
  apt-get install -y libmpc3 libgmp10 libmpfr6 && \
  apt-get clean
COPY --from=pruchain_builder /opt/gnupru /opt/gnupru/
ENV PATH=${PATH}:/opt/gnupru/bin
