FROM docker.io/debian:bookworm-slim as git
RUN \
    apt-get update && \
    apt-get install -y git && \
    apt-get clean

FROM git as retriever
ARG KLIPPER_UPSTREAM=https://github.com/klipper3d/klipper.git
ARG KLIPPER_REF=master
RUN git clone --bare "${KLIPPER_UPSTREAM}" /usr/share/klipper_src && mkdir /usr/src/klipper
ENV GIT_DIR=/usr/share/klipper_src GIT_WORK_TREE=/usr/src/klipper
RUN git checkout "${KLIPPER_REF}"
WORKDIR /usr/src/klipper
RUN git describe --long --tags --always | tee /usr/src/klipper/src/.version

FROM scratch as klipper_holder
COPY --from=retriever /usr/src/klipper/ /
