ARG BASE_IMAGE=kfa_buildbase:latest
FROM ${BASE_IMAGE}
RUN curl -L# 'https://more.musl.cc/10/x86_64-linux-musl/or1k-linux-musl-cross.tgz' | tar -C /opt -xz
ENV PATH=${PATH}:/opt/or1k-linux-musl-cross/bin
