ARG BASE_IMAGE=kfa_buildbase:latest
FROM ${BASE_IMAGE}
RUN \
    apt-get update && \
    apt-get install -y libnewlib-arm-none-eabi gcc-arm-none-eabi binutils-arm-none-eabi cpp g++ && \
    apt-get clean

