on:
  workflow_call:
    inputs:
      base_image:
        type: string
        default: "ghcr.io/laikulo/kfa_buildbase:latest"
      machine:
        type: string
        default: "linux"

jobs:
  build_machine_container:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      built_imageid: ${{ steps.build.outputs.imageid }}
      built_image: ${{ steps.meta.outputs.tags }}@${{ steps.build.outputs.imageid }}
    steps:
      - uses: actions/checkout@v4

      - name: setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images:
            ghcr.io/laikulo/kfa_build_${{ on.workflow_call.inputs.machine }}

      - name: Docker Build
        uses: docker/build-push-action@v5
        id: build
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: ./kfa_build_${{ on.workflow_call.inputs.machine }}
          file: ./kfa_build_${{ on.workflow_call.inputs.machine }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  extract_delta_layer:
    runs-on: ubuntu-latest
    needs:
      - build_machine_container
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: extract
        run: |
          mkdir out
          podman pull "${{ on.workflow_call.inputs.machine }}"
          podman pull "${{ needs.build_base_container.outputs.built_image }}"
          ./bin/extract-delta "${{ on.workflow_call.inputs.machine }}" "${{ needs.build_base_container.outputs.built_image }}" out/kfa_build_${{ on.workflow_call.inputs.machine }}.sfs
      - uses: actions/upload-artifact@v4
        with:
          path: out/kfa_build_${{ on.workflow_call.inputs.machine }}.sfs
          name: 'kfa_build_${{ on.workflow_call.inputs.machine }}.sfs'