---
on:
  workflow_dispatch:

name: Build KFA Containers and Layers

jobs:
  build_base_container:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      built_imageid: ${{ steps.build.outputs.imageid }}
      built_image: ${{ steps.meta.outputs.tags }}@${{ steps.build.outputs.imageid }}
    steps:
    - uses: actions/checkout@v4
  
    - name: setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into ghcr.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
  
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images:
          ghcr.io/laikulo/kfa_buildbase

    - name: Docker Build
      uses: docker/build-push-action@v5
      id: build
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: ./kfa_buildbase
        file: ./kfa_buildbase/Containerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  extract_base_layer:
    runs-on: ubuntu-latest
    needs:
      - build_base_container
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: extract
        run: |
          mkdir out
          podman pull "${{ needs.build_base_container.outputs.built_imate }}"
          ./bin/extract-base-layer "${{ needs.build_base_container.outputs.built_image }}" out/kfa_buildbase.sfs
      - uses: actions/upload-artifact@v4
        with:
          path: out/kfa_buildbase.sfs