---
on:
  workflow_dispatch:

name: Build KFA Containers and Layers

jobs:
  build_base_container:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
  
    - name: setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log into ghcr.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
  
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images:
          ghcr.io/laikulo/kfa_buildbase

    - name: Docker Build
      uses: docker/build-push-action@v5
      with:
        push: ${{ github.event_name != 'pull_request' }}
        context: ./kfa_buildbase
        file: ./kfa_buildbase/Containerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
